move_group:
  ros__parameters:
    planning_scene_monitor:
      publish_planning_scene: true
      publish_geometry_updates: true
      publish_state_updates: true
      publish_transforms_updates: true
